name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: |
        npm install
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        DEPLOY_KEY: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_DIR: ./public
        CNAME: albertodoblado.com

